export default {
	cat_tower_level_1: {
		level: 1,
		towerType: 'cat_tower_level_1',
		nextLevel: 'cat_tower_level_2',
		health: 500,
		damage: 50,
		price: 100,
		attackSpeed: 200,
		projectile: 'wool_ball',
	},
	cat_tower_level_2: {
		level: 2,
		towerType: 'cat_tower_level_2',
		nextLevel: 'cat_tower_level_3',
		health: 500 + 500 * 2,
		damage: 50 * 2,
		price: 200,
		attackSpeed: 170,
		projectile: 'wool_ball',
	},
	cat_tower_level_3: {
		level: 3,
		towerType: 'cat_tower_level_3',
		nextLevel: 'cat_tower_level_4',
		health: 500 + 500 * 3,
		damage: 50 * 3,
		price: 400,
		attackSpeed: 120,
		projectile: 'wool_ball',
	},
	cat_tower_level_4: {
		level: 4,
		towerType: 'cat_tower_level_4',
		nextLevel: 'cat_tower_level_5',
		health: 500 + 500 * 4,
		damage: 50 * 4,
		price: 800,
		attackSpeed: 120,
		projectile: 'wool_ball',
	},
	cat_tower_level_5: {
		level: 5,
		towerType: 'cat_tower_level_5',
		nextLevel: 'cat_tower_level_6',
		health: 500 + 500 * 5,
		damage: 50 * 5,
		price: 1600,
		attackSpeed: 120,
		projectile: 'wool_ball',
	},
	cat_tower_level_6: {
		level: 6,
		towerType: 'cat_tower_level_6',
		nextLevel: 'cat_tower_level_7',
		health: 500 + 500 * 6,
		damage: 50 * 6,
		price: 3200,
		attackSpeed: 120,
		projectile: 'wool_ball',
	},
	cat_tower_level_7: {
		level: 7,
		towerType: 'cat_tower_level_7',
		nextLevel: 'cat_tower_level_8',
		health: 500 + 500 * 7,
		damage: 50 * 7,
		price: 6400,
		attackSpeed: 120,
		projectile: 'wool_ball',
	},
	cat_tower_level_8: {
		level: 8,
		towerType: 'cat_tower_level_8',
		nextLevel: 'cat_tower_level_9',
		health: 500 + 500 * 8,
		damage: 50 * 8,
		price: 12800,
		attackSpeed: 120,
		projectile: 'wool_ball',
	},
	cat_tower_level_9: {
		level: 9,
		towerType: 'cat_tower_level_9',
		nextLevel: null,
		health: 500 + 500 * 9,
		damage: 50 * 9,
		price: 25600,
		attackSpeed: 120,
		projectile: 'wool_ball',
	},
	pikachu_tower_level_1: {
		level: 1,
		towerType: 'pikachu_tower_level_1',
		nextLevel: 'pikachu_tower_level_2',
		health: 10,
		damage: 100,
		attackSpeed: 170,
		price: 200,
		projectile: 'lightning',
	},
	pikachu_tower_level_2: {
		level: 2,
		towerType: 'pikachu_tower_level_2',
		nextLevel: 'pikachu_tower_level_3',
		health: 750 + 750 * 2,
		damage: 100 * 2,
		price: 400,
		attackSpeed: 170,
		projectile: 'lightning',
	},
	pikachu_tower_level_3: {
		level: 3,
		towerType: 'pikachu_tower_level_3',
		nextLevel: 'pikachu_tower_level_4',
		health: 750 + 750 * 3,
		damage: 100 * 3,
		price: 800,
		attackSpeed: 170,
		projectile: 'lightning',
	},
	pikachu_tower_level_4: {
		level: 4,
		towerType: 'pikachu_tower_level_4',
		nextLevel: 'pikachu_tower_level_5',
		health: 750 + 750 * 4,
		damage: 100 * 4,
		price: 1600,
		attackSpeed: 120,
		projectile: 'lightning',
	},
	pikachu_tower_level_5: {
		level: 5,
		towerType: 'pikachu_tower_level_5',
		nextLevel: 'pikachu_tower_level_6',
		health: 750 + 750 * 5,
		damage: 100 * 5,
		price: 3200,
		attackSpeed: 120,
		projectile: 'lightning',
	},
	pikachu_tower_level_6: {
		level: 6,
		towerType: 'pikachu_tower_level_6',
		nextLevel: 'pikachu_tower_level_7',
		health: 750 + 750 * 6,
		damage: 100 * 6,
		price: 6400,
		attackSpeed: 120,
		projectile: 'lightning',
	},
	pikachu_tower_level_7: {
		level: 7,
		towerType: 'pikachu_tower_level_7',
		nextLevel: 'pikachu_tower_level_8',
		health: 750 + 750 * 7,
		damage: 100 * 7,
		price: 12800,
		attackSpeed: 80,
		projectile: 'lightning',
	},
	pikachu_tower_level_8: {
		level: 8,
		towerType: 'pikachu_tower_level_8',
		nextLevel: 'pikachu_tower_level_9',
		health: 750 + 750 * 8,
		damage: 100 * 8,
		price: 25600,
		attackSpeed: 80,
		projectile: 'lightning',
	},
	pikachu_tower_level_9: {
		level: 9,
		towerType: 'pikachu_tower_level_9',
		nextLevel: null,
		health: 750 + 750 * 9,
		damage: 100 * 9,
		price: 51200,
		attackSpeed: 80,
		projectile: 'lightning',
	},
	rabbit_tower_level_1: {
		level: 1,
		towerType: 'rabbit_tower_level_1',
		nextLevel: 'rabbit_tower_level_2',
		health: 10,
		damage: 300,
		price: 500,
		attackSpeed: 120,
		projectile: 'carrot',
	},
	rabbit_tower_level_2: {
		level: 2,
		towerType: 'rabbit_tower_level_2',
		nextLevel: 'rabbit_tower_level_3',
		health: 1000 + 1000 * 2,
		damage: 300 * 2,
		price: 1000,
		attackSpeed: 120,
		projectile: 'carrot',
	},
	rabbit_tower_level_3: {
		level: 3,
		towerType: 'rabbit_tower_level_3',
		nextLevel: 'rabbit_tower_level_4',
		health: 1000 + 1000 * 3,
		damage: 300 * 3,
		price: 2000,
		attackSpeed: 120,
		projectile: 'carrot',
	},
	rabbit_tower_level_4: {
		level: 4,
		towerType: 'rabbit_tower_level_4',
		nextLevel: 'rabbit_tower_level_5',
		health: 1000 + 1000 * 4,
		damage: 300 * 4,
		price: 4000,
		attackSpeed: 90,
		projectile: 'carrot',
	},
	rabbit_tower_level_5: {
		level: 5,
		towerType: 'rabbit_tower_level_5',
		nextLevel: 'rabbit_tower_level_6',
		health: 1000 + 1000 * 5,
		damage: 300 * 5,
		price: 8000,
		attackSpeed: 90,
		projectile: 'carrot',
	},
	rabbit_tower_level_6: {
		level: 6,
		towerType: 'rabbit_tower_level_6',
		nextLevel: 'rabbit_tower_level_7',
		health: 1000 + 1000 * 6,
		damage: 300 * 6,
		price: 16000,
		attackSpeed: 90,
		projectile: 'carrot',
	},
	rabbit_tower_level_7: {
		level: 7,
		towerType: 'rabbit_tower_level_7',
		nextLevel: 'rabbit_tower_level_8',
		health: 1000 + 1000 * 7,
		damage: 300 * 7,
		price: 32000,
		attackSpeed: 60,
		projectile: 'carrot',
	},
	rabbit_tower_level_8: {
		level: 8,
		towerType: 'rabbit_tower_level_8',
		nextLevel: 'rabbit_tower_level_9',
		health: 1000 + 1000 * 8,
		damage: 300 * 8,
		price: 64000,
		attackSpeed: 60,
		projectile: 'carrot',
	},
	rabbit_tower_level_9: {
		level: 9,
		towerType: 'rabbit_tower_level_9',
		nextLevel: null,
		health: 1000 + 1000 * 9,
		damage: 300 * 9,
		price: 128000,
		attackSpeed: 60,
		projectile: 'carrot',
	},
	fernando_torres: {
		level: 4,
		towerType: 'fernando_torres',
		health: 100000,
		damage: 100000,
		price: 3000,
		attackSpeed: 50,
		projectile: 'football_ball',
	},
};
